spring.application.name=autowashpro
spring.profiles.active=dev
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AutoWashPro;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PayOS
payos.payment-api-url=https://api-merchant.payos.vn/v2/payment-requests
payos.client-id=9ca89c8f-4048-4a53-ad27-d45850a5f705
payos.api-key=6d0ebb03-8073-4c6b-90dd-33d3593d12bb
payos.checksum-key=1289a6af30332ae9b008dd5c79a1339de19847299845feed92fa8b9d79b0afb1
payos.return-url=http://localhost:5173/payment/success
payos.cancel-url=http://localhost:5173/payment/cancel

spring.jackson.serialization.write-dates-as-timestamps=false